-- Migration: Add stock_recommendations table
-- Created: 2025-10-20
-- Description: Creates the stock_recommendations table to store stock analysis recommendations

-- Create stock_recommendations table
CREATE TABLE IF NOT EXISTS stock_recommendations (
    id VARCHAR PRIMARY KEY,
    session_id VARCHAR NOT NULL,
    user_id VARCHAR NOT NULL,
    recommendation JSONB NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),

    -- Foreign key constraints
    CONSTRAINT fk_stock_recommendations_session
        FOREIGN KEY (session_id)
        REFERENCES conversation_sessions(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_stock_recommendations_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_stock_recommendations_session_id
    ON stock_recommendations(session_id);

CREATE INDEX IF NOT EXISTS idx_stock_recommendations_user_id
    ON stock_recommendations(user_id);

CREATE INDEX IF NOT EXISTS idx_stock_recommendations_created_at
    ON stock_recommendations(created_at DESC);

-- Add comment to table
COMMENT ON TABLE stock_recommendations IS 'Stores stock analysis recommendations generated by the stock analyser agent';
COMMENT ON COLUMN stock_recommendations.id IS 'Unique identifier for the recommendation';
COMMENT ON COLUMN stock_recommendations.session_id IS 'Reference to the conversation session';
COMMENT ON COLUMN stock_recommendations.user_id IS 'Reference to the user who requested the analysis';
COMMENT ON COLUMN stock_recommendations.recommendation IS 'JSON object containing the complete recommendation data including allocation breakdown and individual stock recommendations';
COMMENT ON COLUMN stock_recommendations.created_at IS 'Timestamp when the recommendation was created';
